#!/bin/bash
source _helpers.sh
if prompt "Symlink dotfiles?"; then
  if [[ $(python --version 2>&1) =~ ^Python\ 3\. ]]; then
    ./dotphile3
  else
    ./dotphile
  fi
fi

function install_cmd() {
  local cmd=''       # Binary command of interest
  local pkg=''       # Name of package that contains command, sometimes differs from --cmd
  local installer='' # Mutually exclusive with --custom
  local custom=''    # Mutually exclusive with --installer
  while :; do
    case $1 in
      --cmd=?*)
        cmd="${1#*=}"; shift;
        ;;
      --pkg=?*)
        pkg="${1#*=}"; shift;
        ;;
      --installer=?*)
        installer="${1#*=}"; shift;
        ;;
      --custom=?*)
        custom="${1#*=}"; shift;
        ;;
      ?*)
        echo "unknown option \"$1\""
        exit 1
        ;;
      *)
        break;
    esac
  done

  if [[ $(command -v "$cmd") ]]; then
    echo -e " ${GREEN}✓${NORMAL} $cmd installed"
  elif prompt " ${RED}✗${NORMAL} missing $cmd from package $pkg - install?"; then
    if [[ -n $custom ]]; then
      $custom
    else
    install_package $pkg $installer
    fi
  fi
}

function install_fzf_on_linux(){
  [[ -d "$HOME/.fzf" ]] && echo_and_run rm -rf "$HOME/.fzf"
  echo_and_run git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  echo_and_run ~/.fzf/install --all
}

function install_git_number_on_linux() {
  echo_and_run mkdir -p ~/git/git-number
  echo_and_run git clone https://github.com/holygeek/git-number.git ~/git/git-number
  (
    cd ~/git/git-number || exit 1;
    echo_and_run sudo make install;
  );
}

#Custom Installs
install_cmd --cmd=fzf --custom=install_fzf_on_linux
install_cmd --cmd=git-number --custom=install_git_number_on_linux

# Pamac Installs
install_cmd --cmd=zsh --pkg=zsh --installer=pamac
install_cmd --cmd=rg --pkg=ripgrep --installer=pamac
install_cmd --cmd=tmux --pkg=tmux --installer=pamac
install_cmd --cmd=autojump --pkg=autojump --installer=pamac
install_cmd --cmd=node --pkg=nodejs --installer=pamac
install_cmd --cmd=shellcheck --pkg=shellcheck --installer=pamac

# Pip Installs
install_cmd --cmd=vint --pkg=vim-vint --installer=pip # vimscript linting

vim/setup-vim.sh
zsh/setup-zsh.sh
osx/set-defaults.sh
